patternplate/patternplate

source/binary/patternplate.js, source/library/init/index.js
=> fix: use sander correctly

readme.md, source/library/init/index.js
=> fix: always print the install instruction after init

docs/reference/widgets.md
The examples and snippets were not the same
closes #166
=> docs: correct examples

packages/client/src/app/components/pattern/pattern-sheet.js
Wraps Links in a wrapper to allow adding `margin-left` on children > 1 
fixes #167
=> fix: add spacing around tags in lists

packages/components/src/cover/index.js
But retaining uppercase in headlines.
=> docs: source of truth in lowercase

docs/why.md
=> docs: minor edits

packages/client/src/app/components/pattern/index.js
Width of component iframe increased to a max of 1920px: https://github.com/patternplate/patternplate/issues/227
=> Increased max-width of the component view from 1240px to 1920px

packages/demo-client/index.js, packages/webpack-entry/src/loader.js
=> fix: fixes minor compability issues for IE11

packages/api/src/demo.js
This feature makes it possible to asynchronously render demo content.
This enables tools like LESS or SASS to hook into the render process for demos. Example could be:
```javascript
/* imports ... */
module.exports = render;
async function render(input, context) {
/* other code ... */
const lessSource = '...'; // Read less file
const css = await less.render(lessSource, options);
const copy = merge({}, input, { html, css: () => css });
return renderDefault(copy);
}
```
=> feat: apply asynchronous rendering to demo

packages/api/src/demo.js
Follow-up for #234.
Tested with the internal component library. 
@MartinHelmut  Could you check if this retains support for your use case?
=> fix: restore support for sync renderers #235

packages/api/src/cover.js, packages/cli/src/build/index.js
This adds pattern missing context to demo and cover render. It also awaits the render for cover.
=> feat: add missing pattern context to demo and cover render

packages/api/src/compiler-worker.js, packages/api/src/create-compiler.js, packages/validate-config/package.json, packages/webpack-entry/src/loader.js, yarn.lock
=> fix: normalize import ids on win32

packages/components/src/markdown/demo.js, packages/components/src/markdown/index.js
See #245 
Changes in effect here: https://patternplate.github.io/preview/245/
=> style: improve table styling

docs/guides/getting-started.md
@marionebl: Up next Guide: Build a component is broken  https://patternplate.github.io/doc/docs/guides/getting-started-app?reference-enabled=true&guides-enabled=true
=> Fix broken link - Guide: Build a component.

docs/reference/configuration.md, packages/client/src/app/containers/application.js, packages/components/src/main-navigation/index.js, packages/types/src/index.ts
Now it is possible to switch the components on and off through the `patternplate.config.js`.
=> feat(navigation): configuration option to show or hide the components

packages/client/src/app/components/search.js, packages/client/src/app/containers/search.js
=> fix: linking in search does not extend the url anymore

README.md, components/legacy/src/cover/index.js, docs/about.md, docs/gitter.md
Add Links to the patternplate Gitter organization at https://gitter.im/patternplate/Lobby.
=> docs: link to gitter org where relevant

components/legacy/src/logo.js, packages/client/src/app/client.js, packages/client/src/app/components/favicon.js, packages/client/src/app/containers/logo.js
=> fix: honor favicon and logo settings

components/legacy/src/cover/index.js, packages/api/src/types.ts, packages/render-default/render.js, packages/render-styled-components/render.js
=> fix: propagate content.head through styled-components renderer

docs/reference/configuration.md
Small correction on the docs for theming.
=> fix(docs): corrected property name for the ui colorwarning
